version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    networks:
      - laravel

  web:
    image: nginx:alpine
    container_name: laravel-web
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_TCP_PORT=3306
    ports:
      - 3310:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel

  composer:
    image: composer
    container_name: laravel-composer
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    entrypoint: ["composer"]
    networks:
      - laravel

networks:
  laravel:

volumes:
  mysql-data:
